<?php
ob_start("ob_gzhandler");
require('connect.php');
?>
<html>
    <head>
    	<link rel='stylesheet' type='text/css' href='../style/notifyscreen.css' />
		<script type="text/javascript" src="/java/jquery-1.7.2.min.js"></script>
    </head>
    <body onLoad="load()">
		<?php
        
        if (!isset($email))
        {
            $email = mysql_real_escape_string($_GET['email']);
        }
        
        if (!isset($type))
        {
            $type = mysql_real_escape_string($_GET['type']);
        }
        
        //account activation----------------------------------------------------------------------------------------------------------
        
        if ($type == 'activate')
        {
            if (!isset($code))
            {	
                require ("connect.php");
                $query = mysql_query("SELECT * FROM users WHERE email='".$email."'");
                $row = mysql_fetch_array($query);
                $code = $row['token'];
            }
            ini_set("SMTP", "mail.iinet.net.au");
            
            $to = "".$email."";
            $subject = "Activate your Yew Tv account";
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr align='center'>
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Activate Your Account</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Click the link below or copy it into your address bar to activate your account,
                        <br><br>
                       <a href='http://www.yew.tv/accounts/activate.php?code=".$code."'>yew.tv/accounts/activate.php?code=".$code."</a>
                        <br><br>Cheers.</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                    <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
        
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
          	$return = mail($to,$subject,$message,$headers);
		   
		  	if ($return)
			{
				echo "<div class='center' ><br>Check your email to activate your account.</div>";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
            
            header("Refresh: 3;url=../login.php");
        }
        
        //reset password temporary link----------------------------------------------------------------------------------------------------------
        
        if ($type == 'password')
        {
            //set time limit in login column as +1 day & get code
            require ("connect.php");
            
            $code = rand(23456789,98765432);
            
            $query = mysql_query("UPDATE users SET last_login = NOW() + INTERVAL 24 HOUR, token = ".$code." WHERE email='".$email."'");
            ini_set("SMTP", "mail.iinet.net.au");
            $to = "".$email."";
            $subject = "Reset your Yew Tv password"; 
            $from = "auto@yew.tv";
            $headers = "From:" . $from;
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr >
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Change Password</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Click the link below or copy it into your address bar to change your password,
                        <br><br>
                       <a href='http://www.yew.tv/accounts/gateway.php?code=".$code."&email=".$email."'>yew.tv/accounts/gateway.php?code=".$code."&email=".$email."</a>
                        <br><br>Cheers.</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                      <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
            $return = mail($to,$subject,$message,$headers);
            
			if ($return)
			{
				 echo "<div class='center' ><br>Check your email to change your password.</div>";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
           header("Refresh: 3;url=../login.php");
        }
        
        //change email----------------------------------------------------------------------------------------------------------
        if ($type == 'emailchange')
        {
            require ("connect.php");
            $seush = session_name("suesh_name");
            session_set_cookie_params(0, '/', '.yew.tv');
            session_start();
        
            $query = mysql_query("SELECT token FROM users WHERE session='".$_SESSION['sesh']."' ");
            $row = mysql_fetch_array($query);
            $code = $row['token'];
            
            ini_set("SMTP", "mail.iinet.net.au");
            
            $to = "".$email."";
            $subject = "Set this email as your new email address.";
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr >
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Change Your Email Address.</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Click the link below or copy it into your address bar to save your new email address,
                        <br><br>
                       <a href='http://www.yew.tv/account.php?code=".$code."&email=".$email."'>yew.tv/account.php?code=".$code."&email=".$email."</a>
                        <br><br>Cheers.</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                        <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
            $return = mail($to,$subject,$message,$headers);
            
			if ($return)
			{
				echo "<div class='center' ><br>Check your new email to verify your new email address.</div>";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
			
            header("Refresh: 3;url=../account.php");
        }
        
        //reports----------------------------------------------------------------------------------------------------------
        
        if ($type == 'report')
        {
            //report broken link---------------------------------------------------------------------------------------------------------
            $id = mysql_real_escape_string($_GET['id']);
            require ("connect.php");
            $query = mysql_query("SELECT title, date FROM videos WHERE id='".$id."'");
            while ($row = mysql_fetch_assoc($query))
            {
                $title = $row['title'];
                $timestamp = $row['date'];
            }
            $date = strtotime($timestamp);
            $cleandate = date("d-m-Y", $date);
            session_start();
            
            ini_set("SMTP", "mail.iinet.net.au");
            
            $to = "".$email."";
            $subject = "'".$title."' has been removed";
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr >
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Submission Removal</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Your video titled; ".$title.", uploaded on ".$cleandate." was removed on one of the below grounds:
                        <br><br>
                       <ol>
                            <li>
                                The video no longer was available from the host.
                            </li>
                            <li>
                                The information submitted was inappropriate.
                            </li>
                            <li>
                                The film was not yours.
                            </li>
                       </ol>
                        <br><br>Sorry.</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                       <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
            $return = mail($to,$subject,$message,$headers);
            
			if ($return)
			{
				echo "email sent";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
            
            header("Refresh: 2;url=http://yew.tv/ladmin/reported.php");
        }
        //Video approve/deny---------------------------------------------------------------------------------------------------------
        //approve
        if ($type == 'videoapprove')
        {
            $id = mysql_real_escape_string($_GET['id']);
            require ("connect.php");
            $query = mysql_query("SELECT title, date FROM videos WHERE id='".$id."'");
            while ($row = mysql_fetch_assoc($query))
            {
                $title = $row['title'];
                $timestamp = $row['date'];
            }
            $date = strtotime($timestamp);
            $cleandate = date("d-m-Y", $date);
            session_start();
            
            ini_set("SMTP", "mail.iinet.net.au");
            
            $to = "".$email."";
            $subject = "'".$title."' has been approved.";
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr >
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Submission Approved.</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Your video titled; '".$title."', uploaded on ".$cleandate." has been approved for our competition!
                        <br><br>
                        YEW!</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                       <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
            $return = mail($to,$subject,$message,$headers);
            
			if ($return)
			{
				echo "email sent";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
            
            header("Refresh: 2;url=http://yew.tv/ladmin/ladmin.php");
        }
        //deny
        if ($type == 'videodeny')
        {
            $id = mysql_real_escape_string($_GET['id']);
            require ("connect.php");
            $query = mysql_query("SELECT title, date FROM videos WHERE id='".$id."'");
            while ($row = mysql_fetch_assoc($query))
            {
                $title = $row['title'];
                $timestamp = $row['date'];
            }
            $date = strtotime($timestamp);
            $cleandate = date("d-m-Y", $date);
            session_start();
            
            ini_set("SMTP", "mail.iinet.net.au");
            
            $to = "".$email."";
            $subject = "'".$title."' has been denied.";
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr >
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Submission Denied</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Your video titled; '".$title."', uploaded on ".$cleandate." has not made it into this round of our competition, remember; 
			<ul >
				<strong>Requirements:</strong>
					<li>Based on Skateboarding.</li>
					<li>Less than 4 minutes.</li>
					<li>Contains the Yew tv competition screen <a href='http://www.yew.tv/images/download.php'>here</a>. <br>
					<li>Complete ownership of intellectual property.</li>
            </ul>
			<br>
			Please read the 'Detailed Competition Conditions' <a href='http://www.yew.tv/conditions.php'>here</a>.<br><br>
			If your film has already satisfied all these criteria we want you to improve your film and re-submit it.
                        <br><br>
                        Sorry<br> :-/</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                       <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
            $return = mail($to,$subject,$message,$headers);
            
			if ($return)
			{
				echo "email sent";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
			
            header("Refresh: 2;url=http://yew.tv/ladmin/ladmin.php");
        }
        //delete channel------------------------------------------------------------------------------------------------------------------------
        if ($type == 'delete')
        {
            $token = mysql_real_escape_string($_GET['token']);
            require ("connect.php");
            session_start();
            
            $query = mysql_query("SELECT channel FROM users WHERE email='".$email."' AND token = ".$token."");
            while ($row = mysql_fetch_array($query))
            {
                $ChannelDirty = $row['channel'];
            }
            
            $channel = (preg_replace("/[#]/", '', $ChannelDirty));
            
            ini_set("SMTP", "mail.iinet.net.au");
            
            $to = "".$email."";
            $subject = "Delete ".$channel.".yew.tv";
            $message = "
            <html>
            <title>Yew tv email, do not reply</title>
            <body style='display:block; margin:0px; font-family: calibri;'>
            <table width='600px' align='center'  border='0' cellspacing='0' cellpadding='0'>
                <tr >
                    <td>";
                        $numbers = range(1, 5);
						shuffle($numbers);
						foreach ($numbers as $number) {
							if ($number == 1)
							{
								$href = 'http://1.com';
							}
							if ($number == 2)
							{
								$href = 'http://2.com';
							}
							if ($number == 3)
							{
								$href = 'http://3.com';
							}
							if ($number == 4)
							{
								$href = 'http://4.com';
							}
							if ($number == 5)
							{
								$href = 'http://5.com';
							}
							$message .= "<a href='".$href."'><img border='0' style='padding-left:5px;padding-right:5px;' width='110px' height='110px' src='http://www.yew.tv/images/".$number.".png' ></a>";
						}
						$message .= "
                    </td>
                </tr>
                <tr align='center'>
                    <td>
                        <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <h1 style='margin:0px; padding:0px;'>yew.tv - <i>Delete Channel</i></h1>
                       <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                        <p style='margin: 40px;'>Click the link below or copy it into your address bar to delete '".$channel.".yew.tv'.
                        <br><br>yew.tv/accounts/delete.php?code=".$token."&channel=".$channel."<br><br>
                        Please email us if you have any ideas to better our website! <a href='http://mailto:feedback@yew.tv'>give feedback</a>.</p>
                    </td>
               </tr>
               <tr>
                    <tr align='center'>
                    <td>
                    <hr width='600px' style='border:dotted; border-width:1px 0 0 0; '>
                    <p>Do you dig yew tv? chuck us a like.</p>
                      <a href='http://www.facebook.com/www.yew.tv/app_190322544333196' target='_blank' >
         				<img border='0' title='Facebook Like Button' width='200px' height='60px' src='http://www.yew.tv/images/facebook.jpg' alt='Connect on facebook' />
        			</a>
        <p style='font-size:9px;'>This email was automatically generated by www.yew.tv and requested by you.</p>
                    </td>
               </tr>
            </table>
            </body>
        </html>";
            
            $from = "auto@yew.tv";
            $headers = "From: Yew tv <".$from.">\r\n";
            $headers .= "Reply-To:  feedback@yew.tv \r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            
			$return = mail($to,$subject,$message,$headers);
            
			if ($return)
			{
				 echo "<div class='center' ><br>Check your email address to delete ".$channel.".yew.tv.</div>";
			}
			else
			{
				echo "<div class='center' ><br>An error occured, please try again later.</div>";
			}
			
            header("Refresh: 4;url=../submit-a-video.php");
        }
        ?>
    </body>
    <script>
		//--fade in page-----------------------------------------------------------------------------------------
		$('.center').hide();
		function load()
		{
			$('.center').fadeIn(700);
		}
	</script>
</html>